### ISSUE TITLE
WTF BRO

### ISSUE THREAD

**Issue by operationairstrike** [Nekmo/dirhunt#127]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/dirhunt", line 11, in <module>
    load_entry_point('dirhunt==1.0.0', 'console_scripts', 'dirhunt')()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/dirhunt/management.py", line 13, in <module>
    from dirhunt.crawler import Crawler
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/dirhunt/crawler.py", line 22, in <module>
    from dirhunt.sources import Sources
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/dirhunt/sources/__init__.py", line 1, in <module>
    from dirhunt.sources.commoncrawl import CommonCrawl
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/dirhunt/sources/commoncrawl.py", line 2, in <module>
    from json import JSONDecodeError
ImportError: cannot import name JSONDecodeError
~ $ dirhunt
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/dirhunt", line 11, in <module>
    load_entry_point('dirhunt==1.0.0', 'console_scripts', 'dirhunt')()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/dirhunt/management.py", line 13, in <module>
    from dirhunt.crawler import Crawler
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/dirhunt/crawler.py", line 22, in <module>
    from dirhunt.sources import Sources
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/dirhunt/sources/__init__.py", line 1, in <module>
    from dirhunt.sources.commoncrawl import CommonCrawl
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/dirhunt/sources/commoncrawl.py", line 2, in <module>
    from json import JSONDecodeError
ImportError: cannot import name JSONDecodeError
~ $

**Comment by Nekmo** [comment]
Can you please provide more details about the error? What website is it happening on? What is the command? Thanks.

**Comment by operationairstrike** [comment]
Was my fault was using wrong python version bruh
