### ISSUE TITLE
can't run the tool correctly...

### ISSUE THREAD

**Issue by F4kda7** [Nekmo/dirhunt#76]
dirhunt www.sample-website.com --proxies random

Welcome to Dirhunt v0.6.0 using Python 3.7.6
Traceback (most recent call last):
  File "/usr/local/bin/dirhunt", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/dirhunt/management.py", line 162, in main
    catch(hunt)()
  File "/usr/local/lib/python3.7/dist-packages/dirhunt/exceptions.py", line 33, in wrap
    fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/dirhunt/management.py", line 150, in hunt
    not_allow_redirects=not_allow_redirects, proxies=proxies, delay=delay, limit=limit)
  File "/usr/local/lib/python3.7/dist-packages/dirhunt/crawler.py", line 35, in __init__
    self.sessions = Sessions(proxies, delay)
  File "/usr/local/lib/python3.7/dist-packages/dirhunt/sessions.py", line 127, in __init__
    self.sessions = self.create_sessions(proxies or [None])
  File "/usr/local/lib/python3.7/dist-packages/dirhunt/sessions.py", line 138, in create_sessions
    return [Session(self, proxy) for proxy in proxies]
  File "/usr/local/lib/python3.7/dist-packages/dirhunt/sessions.py", line 138, in <listcomp>
    return [Session(self, proxy) for proxy in proxies]
  File "/usr/local/lib/python3.7/dist-packages/dirhunt/sessions.py", line 83, in __init__
    self.proxy = normalize_proxy(self.proxy_name, sessions)
  File "/usr/local/lib/python3.7/dist-packages/dirhunt/sessions.py", line 59, in normalize_proxy
    return next(sessions.proxies_lists[proxy], None)
  File "/usr/local/lib/python3.7/dist-packages/proxy_db/proxies.py", line 56, in __next__
    return self.try_get_proxy()
  File "/usr/local/lib/python3.7/dist-packages/proxy_db/proxies.py", line 49, in try_get_proxy
    self.reload_provider()
  File "/usr/local/lib/python3.7/dist-packages/proxy_db/proxies.py", line 37, in reload_provider
    provider.request(**self.request_options).now()
  File "/usr/local/lib/python3.7/dist-packages/proxy_db/providers.py", line 45, in now
    proxies = self.provider.process_page(requests.request(self.method, self.url), self)
  File "/usr/local/lib/python3.7/dist-packages/proxy_db/providers.py", line 86, in process_page
    return self.process_proxies(self.find_page_proxies(request))
  File "/usr/local/lib/python3.7/dist-packages/proxy_db/providers.py", line 109, in find_page_proxies
    return [self.soup_item(item) for item in items]
  File "/usr/local/lib/python3.7/dist-packages/proxy_db/providers.py", line 109, in <listcomp>
    return [self.soup_item(item) for item in items]
  File "/usr/local/lib/python3.7/dist-packages/proxy_db/providers.py", line 136, in soup_item
    substr = int(re.match('.+substr\((\d+)\).+', script).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

Installation method github
Operating system: Parrot GNU/Linux 4.8
Python version: Python 3
kernel Linux 5.4.0-3parrot1-amd64
the system is udpated

what should i do ?

thanks

**Comment by Nekmo** [comment]
This is a bug. Surely it is a problem with a specific site. Thanks for the report!

**Comment by Nekmo** [comment]
Ok it seems a problem with proxy-db: https://github.com/Nekmo/proxy-db/

**Comment by Nekmo** [comment]
Fixed in proxy-db. Thanks!
