### ISSUE TITLE
Error if the output file is not defined

### ISSUE THREAD

**Issue by hahahahahahahahahahahahahahahah** [Nekmo/dirhunt#77]
```
$ dirhunt --threads 30 --timeout 10 "http://hidden.hidden.com/admin/"
Welcome to Dirhunt v0.6.0 using Python 3.8.2
[403] http://hidden.hidden.com/admin/  (Generic)
[200] http://hidden.hidden.com/  (Generic)
    Index file found: index.html
◇ Finished after 46 seconds
No interesting files detected ¯\_(ツ)_/¯
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/dirhunt", line 11, in <module>
    load_entry_point('dirhunt==0.6.0', 'console_scripts', 'dirhunt')()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/dirhunt-0.6.0-py3.8.egg/dirhunt/management.py", line 166, in main
    catch(hunt)()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/dirhunt-0.6.0-py3.8.egg/dirhunt/exceptions.py", line 33, in wrap
    fn(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/dirhunt-0.6.0-py3.8.egg/dirhunt/management.py", line 162, in hunt
    crawler.create_report()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/dirhunt-0.6.0-py3.8.egg/dirhunt/crawler.py", line 191, in create_report
    json.dump(self.json(), open(self.to_file, 'w'), cls=JsonReportEncoder, indent=4, sort_keys=True)
OSError: [Errno 9] Bad file descriptor
$
```

**Comment by hahahahahahahahahahahahahahahah** [comment]
https://github.com/termux
https://play.google.com/store/apps/details?id=com.termux.api
https://play.google.com/store/apps/details?id=com.termux

**Comment by hahahahahahahahahahahahahahahah** [comment]
```
$ pwd
/data/data/com.termux/files/home/dirhunt
$ uname -a
Linux localhost 4.9.112-perf-gb721abc #1 SMP PREEMPT Tue Feb 25 03:26:51 CST 2020 aarch64 Android
$
```

**Comment by Nekmo** [comment]
This seems like a problem with the development version. You can use the latest stable version from Pypi.

Thanks for the report.

**Comment by Nekmo** [comment]
Fixed. Thanks!
