### ISSUE TITLE
installations error 

### ISSUE THREAD

**Issue by tamjid1971** [Nekmo/dirhunt#81]
when I install  using > pip install dirhunt
it's successfully installed but 
when i use it face this error 
please help me how to prevent it..

root@tamjid:~▶ dirhunt 
Traceback (most recent call last):
  File "/usr/local/bin/dirhunt", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3105, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3089, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3118, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 580, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 593, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.18.4 (/usr/lib/python2.7/dist-packages), Requirement.parse('requests>=2.22.0'), set(['geoip2']))

**Comment by Nekmo** [comment]
I was unable to reproduce it with Python 2 using virtualenvs. Can you run `pip freeze`?

```
[nekmo@homura ~/.virtualenvs]$ mktmpenv -p /usr/bin/python2
created virtual environment CPython2.7.18.final.0-64 in 319ms
  creator CPython2Posix(dest=/home/nekmo/.virtualenvs/tmp-4d1377aba8d6827, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/nekmo/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-4d1377aba8d6827/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-4d1377aba8d6827/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-4d1377aba8d6827/bin/preactivate
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-4d1377aba8d6827/bin/postactivate
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-4d1377aba8d6827/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.


(tmp-4d1377aba8d6827) [nekmo@homura ~/.virtualenvs/tmp-4d1377aba8d6827]$ pip install dirhunt
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting dirhunt
  Using cached dirhunt-0.7.0.tar.gz (33 kB)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.9.1-py2-none-any.whl (111 kB)
     |████████████████████████████████| 111 kB 2.3 MB/s 
Collecting requests
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting click
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting humanize
  Using cached humanize-1.0.0-py2.py3-none-any.whl (51 kB)
Collecting colorama
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting requests-mock
  Using cached requests_mock-1.8.0-py2.py3-none-any.whl (23 kB)
Collecting google
  Downloading google-3.0.0-py2.py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 2.4 MB/s 
Processing /home/nekmo/.cache/pip/wheels/79/9d/4c/0c91b415d404c324991fe530ec3e73104c7ae4f600b15a0ec2/proxy_db-0.2.5-py2.py3-none-any.whl
Collecting futures
  Using cached futures-3.3.0-py2-none-any.whl (16 kB)
Processing /home/nekmo/.cache/pip/wheels/61/e1/9a/a8a59aa36d42252875dd63b54c67095fd80d1054f6304fc257/py2_ipaddress-3.4.2-py2-none-any.whl
Collecting soupsieve<2.0
  Downloading soupsieve-1.9.6-py2.py3-none-any.whl (33 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 7.1 MB/s 
Collecting certifi>=2017.4.17
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting sqlalchemy
  Downloading SQLAlchemy-1.3.18-cp27-cp27mu-manylinux2010_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 7.1 MB/s 
Collecting geoip2
  Using cached geoip2-3.0.0-py2.py3-none-any.whl (23 kB)
Collecting backports.functools-lru-cache; python_version < "3"
  Using cached backports.functools_lru_cache-1.6.1-py2.py3-none-any.whl (5.7 kB)
Collecting maxminddb>=1.5.2
  Downloading maxminddb-1.5.4.tar.gz (282 kB)
     |████████████████████████████████| 282 kB 14.6 MB/s 
Collecting ipaddress; python_version == "2.7"
  Using cached ipaddress-1.0.23-py2.py3-none-any.whl (18 kB)
Building wheels for collected packages: dirhunt, maxminddb
  Building wheel for dirhunt (setup.py) ... done
  Created wheel for dirhunt: filename=dirhunt-0.7.0-py2-none-any.whl size=42060 sha256=b45222e4964c8196bdfd13df2deeb4ce08b6ed038617a8f8b6f53b58aa29ba0b
  Stored in directory: /home/nekmo/.cache/pip/wheels/a8/67/fb/0776b5c0a3b99f25b959be620553be06f2081c7d9e56ec3304
  Building wheel for maxminddb (setup.py) ... done
  Created wheel for maxminddb: filename=maxminddb-1.5.4-cp27-cp27mu-linux_x86_64.whl size=22641 sha256=20669f2537d3437a29242f6fb0788869e5ca2b23b8751ca2beacb2527557b294
  Stored in directory: /home/nekmo/.cache/pip/wheels/a8/b5/b6/97962cef7dbae9d88e81bd2a5c2f34bc0163bd5ce391434a21
Successfully built dirhunt maxminddb
Installing collected packages: backports.functools-lru-cache, soupsieve, beautifulsoup4, urllib3, certifi, chardet, idna, requests, click, humanize, colorama, six, requests-mock, google, sqlalchemy, ipaddress, maxminddb, geoip2, proxy-db, futures, py2-ipaddress, dirhunt
Successfully installed backports.functools-lru-cache-1.6.1 beautifulsoup4-4.9.1 certifi-2020.6.20 chardet-3.0.4 click-7.1.2 colorama-0.4.3 dirhunt-0.7.0 futures-3.3.0 geoip2-3.0.0 google-3.0.0 humanize-1.0.0 idna-2.10 ipaddress-1.0.23 maxminddb-1.5.4 proxy-db-0.2.5 py2-ipaddress-3.4.2 requests-2.24.0 requests-mock-1.8.0 six-1.15.0 soupsieve-1.9.6 sqlalchemy-1.3.18 urllib3-1.25.10


(tmp-4d1377aba8d6827) [nekmo@homura ~/.virtualenvs/tmp-4d1377aba8d6827]$ dirhunt
Welcome to Dirhunt v0.7.0 using Python 2.7.18
•_•) OOPS! Add urls to analyze.
For example: dirhunt http://domain/path

Need help? Then use dirhunt --help
```

**Comment by Nekmo** [comment]
Closed due to inactivity.
